/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as NearbyAttractionsRouteImport } from './routes/nearby-attractions'
import { Route as KandaghatRouteImport } from './routes/kandaghat'
import { Route as HotelNearShimlaRouteImport } from './routes/hotel-near-shimla'
import { Route as HotelNearSadhupulRouteImport } from './routes/hotel-near-sadhupul'
import { Route as HotelInSolanRouteImport } from './routes/hotel-in-solan'
import { Route as HotelInKandaghatRouteImport } from './routes/hotel-in-kandaghat'
import { Route as HotelInChailRouteImport } from './routes/hotel-in-chail'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyAttractionsRoute = NearbyAttractionsRouteImport.update({
  id: '/nearby-attractions',
  path: '/nearby-attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const KandaghatRoute = KandaghatRouteImport.update({
  id: '/kandaghat',
  path: '/kandaghat',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelNearShimlaRoute = HotelNearShimlaRouteImport.update({
  id: '/hotel-near-shimla',
  path: '/hotel-near-shimla',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelNearSadhupulRoute = HotelNearSadhupulRouteImport.update({
  id: '/hotel-near-sadhupul',
  path: '/hotel-near-sadhupul',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelInSolanRoute = HotelInSolanRouteImport.update({
  id: '/hotel-in-solan',
  path: '/hotel-in-solan',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelInKandaghatRoute = HotelInKandaghatRouteImport.update({
  id: '/hotel-in-kandaghat',
  path: '/hotel-in-kandaghat',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelInChailRoute = HotelInChailRouteImport.update({
  id: '/hotel-in-chail',
  path: '/hotel-in-chail',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attractions': typeof AttractionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hotel-in-chail': typeof HotelInChailRoute
  '/hotel-in-kandaghat': typeof HotelInKandaghatRoute
  '/hotel-in-solan': typeof HotelInSolanRoute
  '/hotel-near-sadhupul': typeof HotelNearSadhupulRoute
  '/hotel-near-shimla': typeof HotelNearShimlaRoute
  '/kandaghat': typeof KandaghatRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/restaurant': typeof RestaurantRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attractions': typeof AttractionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hotel-in-chail': typeof HotelInChailRoute
  '/hotel-in-kandaghat': typeof HotelInKandaghatRoute
  '/hotel-in-solan': typeof HotelInSolanRoute
  '/hotel-near-sadhupul': typeof HotelNearSadhupulRoute
  '/hotel-near-shimla': typeof HotelNearShimlaRoute
  '/kandaghat': typeof KandaghatRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/restaurant': typeof RestaurantRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attractions': typeof AttractionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hotel-in-chail': typeof HotelInChailRoute
  '/hotel-in-kandaghat': typeof HotelInKandaghatRoute
  '/hotel-in-solan': typeof HotelInSolanRoute
  '/hotel-near-sadhupul': typeof HotelNearSadhupulRoute
  '/hotel-near-shimla': typeof HotelNearShimlaRoute
  '/kandaghat': typeof KandaghatRoute
  '/nearby-attractions': typeof NearbyAttractionsRoute
  '/restaurant': typeof RestaurantRoute
  '/reviews': typeof ReviewsRoute
  '/rooms': typeof RoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/attractions'
    | '/contact'
    | '/gallery'
    | '/hotel-in-chail'
    | '/hotel-in-kandaghat'
    | '/hotel-in-solan'
    | '/hotel-near-sadhupul'
    | '/hotel-near-shimla'
    | '/kandaghat'
    | '/nearby-attractions'
    | '/restaurant'
    | '/reviews'
    | '/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/attractions'
    | '/contact'
    | '/gallery'
    | '/hotel-in-chail'
    | '/hotel-in-kandaghat'
    | '/hotel-in-solan'
    | '/hotel-near-sadhupul'
    | '/hotel-near-shimla'
    | '/kandaghat'
    | '/nearby-attractions'
    | '/restaurant'
    | '/reviews'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/attractions'
    | '/contact'
    | '/gallery'
    | '/hotel-in-chail'
    | '/hotel-in-kandaghat'
    | '/hotel-in-solan'
    | '/hotel-near-sadhupul'
    | '/hotel-near-shimla'
    | '/kandaghat'
    | '/nearby-attractions'
    | '/restaurant'
    | '/reviews'
    | '/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttractionsRoute: typeof AttractionsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HotelInChailRoute: typeof HotelInChailRoute
  HotelInKandaghatRoute: typeof HotelInKandaghatRoute
  HotelInSolanRoute: typeof HotelInSolanRoute
  HotelNearSadhupulRoute: typeof HotelNearSadhupulRoute
  HotelNearShimlaRoute: typeof HotelNearShimlaRoute
  KandaghatRoute: typeof KandaghatRoute
  NearbyAttractionsRoute: typeof NearbyAttractionsRoute
  RestaurantRoute: typeof RestaurantRoute
  ReviewsRoute: typeof ReviewsRoute
  RoomsRoute: typeof RoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby-attractions': {
      id: '/nearby-attractions'
      path: '/nearby-attractions'
      fullPath: '/nearby-attractions'
      preLoaderRoute: typeof NearbyAttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kandaghat': {
      id: '/kandaghat'
      path: '/kandaghat'
      fullPath: '/kandaghat'
      preLoaderRoute: typeof KandaghatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-near-shimla': {
      id: '/hotel-near-shimla'
      path: '/hotel-near-shimla'
      fullPath: '/hotel-near-shimla'
      preLoaderRoute: typeof HotelNearShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-near-sadhupul': {
      id: '/hotel-near-sadhupul'
      path: '/hotel-near-sadhupul'
      fullPath: '/hotel-near-sadhupul'
      preLoaderRoute: typeof HotelNearSadhupulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-in-solan': {
      id: '/hotel-in-solan'
      path: '/hotel-in-solan'
      fullPath: '/hotel-in-solan'
      preLoaderRoute: typeof HotelInSolanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-in-kandaghat': {
      id: '/hotel-in-kandaghat'
      path: '/hotel-in-kandaghat'
      fullPath: '/hotel-in-kandaghat'
      preLoaderRoute: typeof HotelInKandaghatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-in-chail': {
      id: '/hotel-in-chail'
      path: '/hotel-in-chail'
      fullPath: '/hotel-in-chail'
      preLoaderRoute: typeof HotelInChailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttractionsRoute: AttractionsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HotelInChailRoute: HotelInChailRoute,
  HotelInKandaghatRoute: HotelInKandaghatRoute,
  HotelInSolanRoute: HotelInSolanRoute,
  HotelNearSadhupulRoute: HotelNearSadhupulRoute,
  HotelNearShimlaRoute: HotelNearShimlaRoute,
  KandaghatRoute: KandaghatRoute,
  NearbyAttractionsRoute: NearbyAttractionsRoute,
  RestaurantRoute: RestaurantRoute,
  ReviewsRoute: ReviewsRoute,
  RoomsRoute: RoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
